name: Unit Tests & Coverage Check
on:
  workflow_call:  
    inputs: 
      toml_parent_dir:  
        required: false  
        type: string  
        default: "actions/runPVSTestAction"  
      debug_mode:  
        required: false
        type: boolean  
        default: true  
      environment_usage:  
        required: false  
        type: string  
        default: "poetry"  
      additional_args:
        required: false 
        type: string  
        default: "-v"  
      coverage_gate:  
        required: false  
        type: number
        default: 80

permissions:
  contents: read

jobs:
  run-unit-tests:
    runs-on: zilverton-private-x64-ubuntu
    defaults:
      run:
        working-directory: actions/runPVSTestAction

    steps:
      - name: Checkout test code from BruteSquad repo
        uses: actions/checkout@v3
        with:
          repository: zilvertonz/silverton-dataops-brutesquad-example
          ref: feature_DATAOPSInternal-pvs-test-ar1-unit-testing
          token: ${{ secrets.GITHUB_TOKEN }}
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [[ "${{ inputs.environment_usage }}" == "poetry" ]]; then
            curl -sSL https://install.python-poetry.org | python3 -
            export PATH="$HOME/.local/bin:$PATH"
            poetry install
          else
            pip install -r requirements.txt || true
            pip install pytest coverage
          fi

      - name: Run Shared Unit Test Action
        uses: zilvertonz/shared-github-actions/test/python@main
        with:
          toml_parent_dir: "runPVSTestAction"
          debug_mode: true
          environment_usage: "pip"
          additional_args: "-v"
          coverage_gate: 85
